"""Manual test cases for SufiSupportHub, derived from the sufi-support-hub source.

Each module: code, title, pre (preconditions), features (feature map rows:
(feature, url/route, roles)), cases [(scenario & steps, expected result, priority)].
Priority: H = must pass for release, M = should pass, L = nice to have.
"""

MODULES = [
    # ------------------------------------------------------------------ PUBLIC
    {
        "code": "HO",
        "title": "Hosting, Domain, HTTPS & Error Pages",
        "pre": "Test from a normal browser and from a private/incognito window.",
        "features": [
            ("HTTPS redirect, canonical domain, error pages", "sufisupporthub.com", "All"),
        ],
        "cases": [
            ("Open http://sufisupporthub.com.", "301 redirect to https://sufisupporthub.com. Padlock shown, certificate valid and not expiring soon.", "H"),
            ("Open http://www.sufisupporthub.com and https://www.sufisupporthub.com.", "Both resolve over HTTPS without certificate warnings and land on the same site (ideally redirect to one canonical host).", "H"),
            ("Open a URL with a trailing slash, e.g. /news/.", "Redirects (301) to /news without the slash.", "L"),
            ("Open a non-existent page, e.g. /this-page-does-not-exist.", "A 404 page is shown. No stack trace, file paths or framework debug screen.", "H"),
            ("Try to open sensitive files directly: /.env, /composer.json, /composer.lock, /README.md, /storage/logs/laravel.log, /public/.env.", "All return 403 or 404. No file contents are ever displayed.", "H"),
            ("Open /deploy-hook.php with no header.", "Returns 403 “forbidden”. It must never run a deploy without the secret X-Deploy-Token header.", "H"),
            ("Open /storage/app/private/... or guess a scoresheet path, e.g. /polling-results/<file>.jpg.", "Not reachable publicly (404/403). Scoresheets are only served through authenticated routes.", "H"),
            ("Directory listing: open /uploads/, /uploads/news/, /js/, /fonts/.", "No file listing is shown (403 or 404).", "M"),
            ("Trigger a server error safely, e.g. /news/99999999 or /admin/polling-results/abc.", "Friendly 404/500 page. APP_DEBUG must be false in production (no Ignition/Whoops page).", "H"),
            ("Check the favicon and the tab icon on all public pages.", "Correct Sufi Support Hub icon shows (README says logo.png is still a placeholder, so confirm the final logo is live).", "L"),
            ("Open /up (Laravel health check).", "Returns HTTP 200 \u201cApplication up\u201d. Can be used for uptime monitoring.", "L"),
            ("Open /site.webmanifest and /robots.txt.", "Both load. robots.txt does not block the site and includes the line “Sitemap: https://sufisupporthub.com/sitemap.xml”. [Fixed in PR #1]", "L"),
        ],
    },
    {
        "code": "HP",
        "title": "Homepage (/)",
        "pre": "Logged out. At least 1 active team member and 1 active news item exist.",
        "features": [
            ("Homepage: hero, pillars, policy focus, leadership, latest news, join section, footer", "/", "Visitor"),
            ("Policy search box (added by script) and “Across Nigeria” zone cards", "/", "Visitor"),
        ],
        "cases": [
            ("Load the homepage on desktop.", "Page loads fully in under 3 s on broadband. Hero headline types out “Sufi Support Hub (SSH): People + Structure = Momentum.”, and the hero image shows.", "H"),
            ("Open the browser console (F12) while loading the homepage.", "No red JavaScript errors, no failed (404) requests, no CSP-blocked resources.", "M"),
            ("Click each top-nav link: Home, Our Vision, Policies, Leadership, News, Join Us, Contact.", "Each scrolls to its section. There is no “About” link any more, and Contact scrolls to the footer contact details. [Fixed in PR #1]", "H"),
            ("Click “Join the Movement” in the hero.", "Registration modal opens (see module RG).", "H"),
            ("Click “Generate your Poster” in the hero.", "Opens /poster.", "H"),
            ("Scroll to “Our Core Pillars” and “Policy Focus Areas”.", "Cards display correctly, with no overlapping text or broken icons.", "M"),
            ("About 1 s after load, type a word from one policy card into “Search policies”, then clear it.", "Non-matching cards fade (opacity). Clearing the box restores all cards.", "L"),
            ("Leadership section: compare with Admin > Team.", "Shows up to 8 ACTIVE members ordered by sort order, then name. Inactive members are hidden. Social icons show only where a handle is set and open the right profile in a new tab.", "H"),
            ("Click “View Full Team”.", "Opens /team.", "M"),
            ("Latest News section: compare with Admin > News.", "Shows up to 6 ACTIVE items, newest published first. Clicking a card opens /news/{slug}.", "H"),
            ("Click “View All News”.", "Opens /news.", "M"),
            ("Join section: click “Volunteer Now”, the “Join a Chapter” card and the “Vote Smart” card.", "Volunteer opens the registration modal. Join a Chapter opens /join-chapter. Vote Smart opens https://govote.ng/get-pvc.", "H"),
            ("About 1.5 s after load, scroll to “Sufi Support Hub Across Nigeria” and click a zone card.", "Cards show only state counts (North Central reads “6 States + FCT”), with no chapter numbers. Clicking any card opens /join-chapter, with no pop-up alert. [Fixed in PR #1]", "M"),
            ("Footer Quick Links / Get Involved: click every link.", "Quick Links shows Our Vision, Policy Areas and Join Us. Get Involved shows Volunteer (scrolls to Join), Find a Chapter and Vote Smart. Every link goes somewhere, and About Us, Events and Support Us are gone. [Fixed in PR #1]", "M"),
            ("Footer social icons with NO SOCIAL_*_URL values in the server .env.", "No social icons are shown at all (no dead “#” links). [Fixed in PR #1]", "M"),
            ("Set SOCIAL_FACEBOOK_URL (and any other network) in the server .env, then reload the homepage.", "Only the configured networks show an icon, and each opens the official SSH account in a new tab.", "M"),
            ("Footer contact: click the email and phone links.", "mailto:support@innofiniti.ng and tel:+2347067797009 open the mail/phone app. Confirm with the owner that these are the correct SSH contacts.", "M"),
            ("Footer “Privacy Policy | Terms of Service”.", "These are plain text, not links, and no such pages exist. Confirm whether pages are required (NDPR compliance, since personal data is collected).", "M"),
            ("Footer year.", "© shows the current year.", "L"),
            ("Scroll the whole page quickly on a phone.", "The hero parallax and fade-in animations do not cause jank or blank sections.", "L"),
        ],
    },
    {
        "code": "RG",
        "title": "“Join the Movement” Registration Modal (POST /register)",
        "pre": "Logged out. Use a fresh test email (e.g. yourname+ssh01@gmail.com). The polling-unit data is loaded on the server.",
        "features": [
            ("2-step registration modal: name/email/phone, then state/LGA/ward/PU + involvement", "/ (modal) → POST /register", "Visitor"),
        ],
        "cases": [
            ("Open the modal and click Next with all fields empty.", "Stays on step 1, and the Name, Email and Phone borders turn red.", "H"),
            ("Fill Name, Email and Phone, then click Next.", "Step 2 appears with State, LGA, Ward, Polling Unit and Involvement. LGA, Ward and Polling Unit are disabled until the previous field is chosen.", "H"),
            ("Click Back on step 2.", "Returns to step 1 with the values kept.", "M"),
            ("Complete step 2 with a valid state/LGA/ward/unit and involvement = Join a Chapter. Submit.", "Button shows “Submitting...”, then the success message “Thank you for joining the movement!...”. The modal closes after about 3 s and the form resets.", "H"),
            ("Admin > Signups > Registrations: find the record from the previous step.", "Record exists with the correct name, email, phone, state, LGA, ward, polling unit and involvement.", "H"),
            ("Repeat with involvement = General Volunteer.", "Saved with involvement “volunteer”.", "M"),
            ("Submit again with the SAME email but a different name and phone.", "Success message is shown again, but NO duplicate record is created and the ORIGINAL details are NOT changed. This is by design, to stop anyone overwriting other people’s data, and the README now says so.", "H"),
            ("Enter an invalid email (e.g. “abc@”) and try to submit.", "Browser blocks it (type=email), or the server returns an error message. Nothing is saved.", "H"),
            ("Enter a 300-character name, or a phone number longer than 20 characters.", "Error shown (max 255 / 20). Nothing saved.", "M"),
            ("Double-click Submit quickly.", "Only one request is sent (button disables) and only one record is created.", "M"),
            ("Submit more than 5 times within 1 minute from the same IP (use different emails).", "The 6th attempt is rejected (HTTP 429, throttle 5/min). Check that the message shown to the user is understandable, not a blank or JSON error.", "M"),
            ("Tamper test: in DevTools, edit the polling-unit option value to a made-up name and submit.", "Rejected: “The selected state, LGA, ward, and polling unit don't match a real polling unit...”. Nothing saved.", "H"),
            ("Tamper test: set involvement to a value other than chapter/volunteer.", "Rejected with a validation error.", "M"),
            ("Enter a name with an HTML/script payload, e.g. <script>alert(1)</script>.", "Saved or rejected, but never executed. It shows as plain text in Admin > Signups and Members.", "H"),
            ("Close the modal with X and by clicking outside it.", "Modal closes both ways.", "L"),
            ("Complete the modal on a phone (375 px wide).", "All fields are visible and scrollable, the keyboard doesn't hide the Submit button, and the dropdowns work.", "H"),
        ],
    },
    {
        "code": "LC",
        "title": "Location Cascade (State → LGA → Ward → Polling Unit)",
        "pre": "Used by the homepage modal, /join-chapter and admin promotion screens.",
        "features": [
            ("Location lookup APIs", "/locations/{state}/lgas, /{lga}/wards, /{ward}/units", "Visitor"),
        ],
        "cases": [
            ("Choose a state.", "The LGA list loads for that state only, sorted A–Z. Ward and Polling Unit reset and stay disabled.", "H"),
            ("Choose an LGA, then a ward.", "Wards and then units load correctly for the chosen parent. No duplicates.", "H"),
            ("Change the state after choosing all four fields.", "LGA, ward and unit are cleared and reloaded. No stale values remain.", "H"),
            ("Pick names containing spaces, slashes, apostrophes or hyphens (e.g. “Abuja Municipal”, a ward with “/”).", "Lists still load correctly (values are URL-encoded).", "M"),
            ("Open /locations/Kano/lgas directly in the browser.", "Returns a JSON array of LGA names.", "L"),
            ("Spot-check 3 states against INEC data: LGA count and a known ward/unit.", "Data matches the official source. No missing states (36 + FCT).", "M"),
            ("Throttle the network to Slow 3G in DevTools and use the cascade.", "Dropdowns eventually populate, and the user can't submit before the unit list loads.", "M"),
        ],
    },
    {
        "code": "CH",
        "title": "Join a Chapter (/join-chapter)",
        "pre": "Logged out. Use a fresh test email.",
        "features": [
            ("Join a Chapter form", "/join-chapter → POST /join-chapter", "Visitor"),
        ],
        "cases": [
            ("Open /join-chapter from the homepage card and from the footer “Find a Chapter”.", "Page loads with the nav “back to Home” link, the form and a working location cascade.", "H"),
            ("Submit a complete valid form.", "Redirects back with the green message “Thank you for joining! Your chapter team will be in touch.” It no longer mentions email. [Fixed in PR #1]", "H"),
            ("Admin > Signups > Chapter Members.", "New record present with the correct details.", "H"),
            ("Check the tester’s inbox after joining.", "No email arrives (none is sent yet), which matches the message. If the owner later adds a welcome email, update this case.", "L"),
            ("Submit with the same email again (different details).", "Success is shown, there is no duplicate, and the original details are unchanged.", "H"),
            ("Tamper the polling-unit value (DevTools) and submit.", "Rejected. A red error box above the form says the state, LGA, ward and polling unit don’t match a real polling unit. Nothing is saved. [Fixed in PR #1]", "H"),
            ("Submit with required fields removed (DevTools: remove the “required” attribute).", "Nothing saved. The red error box lists each missing field.", "H"),
            ("After a failed submission, check the fields.", "Name, email and phone keep the typed values (old input).", "L"),
            ("Submit more than 5 times in 1 minute.", "The 6th is rejected with 429 “Too Many Requests”.", "M"),
            ("Complete the form on a phone.", "Layout fits the screen and all dropdowns are usable.", "H"),
        ],
    },
    {
        "code": "PO",
        "title": "Poster Generator (/poster)",
        "pre": "Have a portrait photo (JPG, 1–5 MB), a PNG with transparency and a non-image file ready.",
        "features": [
            ("Personalised campaign poster: upload photo, zoom/drag, add name, download PNG", "/poster", "Visitor"),
        ],
        "cases": [
            ("Open /poster.", "Page shows the name field (max 50 characters), photo upload and a disabled Generate button.", "H"),
            ("Enter a name only.", "Generate stays disabled until a photo is also chosen.", "M"),
            ("Upload a photo.", "Preview and edit canvas appear with the poster background and the photo in the circle.", "H"),
            ("Use Zoom In, Zoom Out, drag the photo, then Reset.", "Photo scales and moves inside the circle. Reset restores the default fit.", "M"),
            ("Enter the name and click Generate.", "Poster renders at 800×800 with the photo in the circle and the NAME IN CAPITALS in the correct place. The success message shows.", "H"),
            ("Click Download.", "Downloads “<Name_With_Underscores>_SufiSupportHub_Poster.png”, which opens correctly and matches the preview.", "H"),
            ("Try a 51-character name, and a name with emoji and Arabic/Hausa characters.", "Input stops at 50 characters. Text renders without boxes and does not overflow the poster.", "M"),
            ("Upload a non-image file (e.g. .pdf, or .exe renamed to .jpg).", "The file is ignored or refused gracefully. The page does not break.", "M"),
            ("Upload a very large photo (15–20 MB, 6000 px).", "Works, or fails gracefully without freezing the tab.", "L"),
            ("Full flow on an iPhone (Safari) and an Android phone (Chrome).", "Upload from camera and gallery works, drag works by touch, and the download saves to the phone (iOS may open the image in a new tab to save).", "H"),
            ("Privacy check: watch the Network tab during the whole flow.", "The photo is NOT uploaded to the server. All processing happens in the browser.", "M"),
        ],
    },
    {
        "code": "NW",
        "title": "Public News (/news, /news/{slug})",
        "pre": "At least 13 active news items (to test pagination), plus 1 inactive item.",
        "features": [
            ("News list (12 per page) and article page with share buttons", "/news, /news/{slug}", "Visitor"),
        ],
        "cases": [
            ("Open /news.", "Shows ACTIVE items only, newest published first, 12 per page, with image, date and title.", "H"),
            ("Use the pagination links («, page numbers, »).", "Correct pages load. The URL shows ?page=N. Nothing is missing or repeated across pages.", "M"),
            ("Open an article.", "Title, date, hero image and full body show. Line breaks are preserved. “Back” goes to /#news.", "H"),
            ("Open the URL of an INACTIVE (unpublished) item, and of a deleted item.", "404 page.", "H"),
            ("Click the Facebook, X and WhatsApp share buttons.", "Each opens a share window pre-filled with the article URL (and title for X/WhatsApp).", "M"),
            ("Article whose body contains <b>, <script> or a link.", "Shows as literal text (escaped). Nothing executes.", "H"),
            ("Article with no image.", "Page still looks right, with no broken image icon.", "L"),
            ("Two articles with the same title.", "Each gets a unique slug/URL and both open correctly.", "M"),
        ],
    },
    {
        "code": "TM",
        "title": "Public Team / Leadership (/team)",
        "pre": "At least 13 active members and 1 inactive member.",
        "features": [
            ("Team list (12 per page) with photos and social links", "/team", "Visitor"),
        ],
        "cases": [
            ("Open /team.", "Active members only, ordered by sort order then name, 12 per page, with photo, role and bio.", "H"),
            ("Pagination.", "All members are reachable. No repeats.", "M"),
            ("Social icons for a member with the Facebook/X/TikTok/Instagram handles set.", "Each opens the correct profile URL in a new tab.", "M"),
            ("Member with no photo.", "A placeholder or initials appear, not a broken image.", "L"),
        ],
    },
    {
        "code": "SE",
        "title": "SEO, Sitemap & Link Previews",
        "pre": "",
        "features": [
            ("sitemap.xml, canonical, Open Graph/Twitter cards, JSON-LD", "/sitemap.xml", "Search engines"),
        ],
        "cases": [
            ("Open /sitemap.xml.", "Valid XML listing /, /team, /news, /join-chapter, /poster and every ACTIVE news article (with lastmod and image). No inactive or deleted articles.", "M"),
            ("View the source of /, /news, a news article and /team.", "Each has a unique <title>, meta description, canonical URL (on https://sufisupporthub.com, not localhost), og:title/og:image and twitter:card.", "M"),
            ("Paste the homepage URL and a news URL into WhatsApp and Facebook (or the Facebook Sharing Debugger).", "Preview card shows the right title, description and image.", "M"),
            ("Check the structured data with Google Rich Results Test on a news article.", "NewsArticle/Organization/Breadcrumb JSON-LD is detected with no errors.", "L"),
            ("Check that /admin/* and /agent/* pages are not in the sitemap.", "They are not listed.", "M"),
            ("Google search: site:sufisupporthub.com.", "Public pages are indexed. No admin or agent pages are indexed.", "L"),
        ],
    },
    # ------------------------------------------------------------------- ADMIN
    {
        "code": "AL",
        "title": "Admin Login, Logout, Lockout & Password Change",
        "pre": "Accounts for National, State, Zonal, LGA and Cluster admins. One newly promoted admin (must change password). One deactivated admin.",
        "features": [
            ("Admin login/logout, lockout, forced first-login password change", "/admin/login, /admin/password/change", "All admins"),
        ],
        "cases": [
            ("Open /admin while logged out.", "Redirects to /admin/login.", "H"),
            ("Log in with a valid National account.", "Lands on the /admin dashboard.", "H"),
            ("Log in with a wrong password.", "“Those credentials do not match our records.” The email is kept and the password is cleared.", "H"),
            ("Log in with a non-existent email.", "Same generic message (does not reveal whether the email exists).", "H"),
            ("Enter a wrong password 5 times for the same email.", "The 6th attempt shows “Too many login attempts. Please try again in N seconds.” Login works again after the wait.", "H"),
            ("Send more than 10 login requests in 1 minute from one IP (any emails).", "Blocked with 429 by the per-IP limit.", "M"),
            ("Open /admin/login while already logged in.", "Redirects straight to the dashboard.", "M"),
            ("First login of a newly promoted admin.", "Forced to /admin/password/change. Any other admin URL redirects back there until the password is changed. Logout still works.", "H"),
            ("Change password with a wrong current password.", "“That is not your current password.”", "H"),
            ("New password shorter than 8 characters, or confirmation mismatch.", "Validation error. Password not changed.", "H"),
            ("Change password correctly.", "Redirect to the dashboard with “Password changed.”. Log out and log in with the new password.", "H"),
            ("Voluntary change: click “Change Password” in the sidebar.", "Same form works any time.", "M"),
            ("Log in with a DEACTIVATED admin account.", "Access is refused with 403 “This admin account has been deactivated.” Check the message is clear (login itself does not pre-check, so this shows after login).", "H"),
            ("While admin A is logged in, National deactivates A. A clicks any link.", "A is logged out immediately and sees 403 deactivated.", "H"),
            ("Click Logout, then press the browser Back button and try an action.", "Redirected to login. The old session no longer works.", "H"),
            ("Agent credentials used on /admin/login.", "Rejected. Agents can only log in at /agent/login.", "H"),
            ("Leave the admin idle for more than 2 hours (SESSION_LIFETIME=120), then click.", "Session expired, redirected to login. No data lost silently in a half-submitted form.", "M"),
        ],
    },
    {
        "code": "AD",
        "title": "Admin Dashboard & Navigation",
        "pre": "Log in as each admin role in turn.",
        "features": [
            ("Dashboard counts and sidebar navigation", "/admin", "All admins"),
        ],
        "cases": [
            ("Open the dashboard as National.", "Four counts: Registrations, Chapter Members, Team Members and News Items, all matching the real totals.", "H"),
            ("Open the dashboard as a State, LGA and Cluster admin in turn.", "Only two counts, Registrations and Chapter Members, covering ONLY that admin’s area (compare with their Signups page). No Team or News counts. [Fixed in PR #1]", "H"),
            ("Click every sidebar link as National.", "Every page opens and the active link is highlighted.", "H"),
            ("As State/Zonal/LGA/Cluster, check the sidebar.", "Team, News, Parties, Elections and Activity Log are NOT shown. Signups, Members, Admins, Polling Agents, Result Review, Situation Room and Trash are shown. [Fixed in PR #1]", "H"),
            ("Admin screens on a phone and a tablet.", "Sidebar collapses or is usable, and tables scroll horizontally without breaking the layout.", "M"),
        ],
    },
    {
        "code": "SU",
        "title": "Signups (Registrations & Chapter Members)",
        "pre": "Registrations and chapter members exist across at least 2 states.",
        "features": [
            ("Signups list with Registrations / Chapter Members tabs (20 per page)", "/admin/signups?type=...", "All admins (scoped)"),
        ],
        "cases": [
            ("National: open Signups and switch between the two tabs.", "Both lists show all records, newest first, 20 per page, with pagination.", "H"),
            ("State admin (e.g. Kano): open Signups.", "Only records whose polling unit is in Kano.", "H"),
            ("Cluster admin: open Signups.", "Only records in that cluster’s ASSIGNED polling units.", "H"),
            ("Non-National: look for a signup whose polling unit did not match (polling_unit_id empty).", "Not visible to non-National admins (fails closed). Visible to National.", "M"),
            ("Change the URL to ?type=anything.", "Falls back to Registrations with no error.", "L"),
            ("A record containing HTML in the name.", "Shown as text, not rendered.", "H"),
        ],
    },
    {
        "code": "AT",
        "title": "Admin – Team Members (National only)",
        "pre": "Logged in as National.",
        "features": [
            ("Team CRUD with photo (crop 500×500), social handles, sort order, active flag", "/admin/team", "National"),
        ],
        "cases": [
            ("Add a member with name, role, bio (≤280 characters), sort order, photo (JPG/PNG/WEBP ≤2 MB), Active ticked and social handles.", "“Team member added.” It appears in the list, on /team and on the homepage in the right order.", "H"),
            ("Leave Name or Role empty.", "Validation error. Not saved.", "H"),
            ("Bio of 281 characters.", "Validation error (max 280).", "M"),
            ("Upload a 3 MB image, a GIF and a PDF.", "Each rejected with a clear message.", "H"),
            ("Enter a full URL (https://x.com/abc) and “@abc” as handles.", "Both are stored as “abc” and the public link opens the correct profile.", "M"),
            ("Edit: replace the photo.", "New photo shows. The old file no longer loads at its URL.", "M"),
            ("Edit: tick “Remove photo”.", "Photo removed and a placeholder shows publicly.", "M"),
            ("Untick Active.", "Member disappears from /team and the homepage but stays in the admin list.", "H"),
            ("Delete a member.", "“Team member removed.” Moves to Trash. Gone from public pages.", "H"),
            ("As a State admin, open /admin/team and /admin/team/create directly.", "403 Forbidden.", "H"),
        ],
    },
    {
        "code": "AN",
        "title": "Admin – News (National only)",
        "pre": "Logged in as National.",
        "features": [
            ("News CRUD with image (crop 800×450), publish date, active flag, auto slug", "/admin/news", "National"),
        ],
        "cases": [
            ("Create an item with title, body, published date, image and Active ticked.", "“News item added.” Appears on /news, the homepage and the sitemap. URL uses a slug from the title.", "H"),
            ("Title empty, body empty, body over 5,000 characters.", "Validation errors. Not saved.", "H"),
            ("Invalid date.", "Validation error.", "M"),
            ("Create with Active unticked.", "Not visible publicly and its URL gives 404.", "H"),
            ("Future published date with Active ticked.", "Record how it behaves: the code shows it immediately and sorts it first. Confirm whether scheduled publishing is expected.", "L"),
            ("Edit the title of a published item.", "Record whether the slug/URL changes. Old shared links should keep working.", "M"),
            ("Replace the image, then Remove image.", "Works as described. Public page updates.", "M"),
            ("Upload a 3 MB or non-image file.", "Rejected.", "H"),
            ("Delete the item.", "Moves to Trash. 404 publicly. Removed from the sitemap.", "H"),
            ("As a non-National admin, open /admin/news.", "403.", "H"),
        ],
    },
    {
        "code": "PA",
        "title": "Admin – Parties (National only)",
        "pre": "Logged in as National.",
        "features": [
            ("Party CRUD: name, abbreviation, colour, logo, sort order, active", "/admin/parties", "National"),
        ],
        "cases": [
            ("Add a party with name, abbreviation (≤20 characters), colour (e.g. #1F5E4A), logo and sort order.", "“Party added.” Listed in sort order. Activity log records party.created.", "H"),
            ("Missing name, abbreviation over 20 characters, negative sort order.", "Validation errors.", "M"),
            ("Edit a party (change colour and logo).", "Saved. The situation room uses the new colour. Log records before/after.", "M"),
            ("Delete a party that has candidates.", "Party moves to Trash AND its candidates are archived too. Log records party.removed.", "H"),
            ("Restore that party from Trash.", "Party returns. The message explains that candidates must be restored individually.", "M"),
            ("As a non-National admin, open /admin/parties.", "403.", "H"),
        ],
    },
    {
        "code": "EL",
        "title": "Admin – Elections & Candidates (National only)",
        "pre": "Elections seeded (e.g. Presidential, Governorship, Senatorial). At least 2 parties.",
        "features": [
            ("Elections list/edit (name, date, open/closed)", "/admin/elections", "National"),
            ("Candidates per election and scope (state / zone / constituency), with photo", "/admin/elections/{id}/candidates", "National"),
        ],
        "cases": [
            ("Open Elections.", "Lists all elections with their candidate counts.", "H"),
            ("Edit an election: change the name and date, untick Active, save.", "“Election updated.” The agent report form no longer shows this election. Log records election.updated.", "H"),
            ("Reactivate it.", "Agents see it again on their report form.", "H"),
            ("Presidential: add a candidate (party, candidate name, running mate, photo).", "Saved with a national scope. The scope picker is not needed.", "H"),
            ("Governorship: add a candidate WITHOUT choosing a state.", "Error “Select a state.”", "H"),
            ("Governorship: add candidates for 2 parties in the same state.", "Candidates are grouped under that state in the list.", "H"),
            ("Senatorial: the scope list shows “State — Zone” pairs. Add a candidate.", "Saved under the correct zone.", "M"),
            ("Choose a non-existent party id (DevTools).", "Validation error.", "M"),
            ("Edit a candidate (untick Active, change photo), then remove the photo.", "Saved. An inactive candidate no longer appears on the agent form.", "H"),
            ("Delete a candidate.", "Moves to Trash. Log records candidate.removed.", "H"),
            ("URL tamper: /admin/elections/{A}/candidates/{candidate-of-B}/edit.", "404 (a candidate can't be edited through another election).", "H"),
            ("As a non-National admin, open any elections URL.", "403.", "H"),
        ],
    },
    {
        "code": "ME",
        "title": "Admin – Members & Promotion (single and bulk)",
        "pre": "Registrations and chapter members in several states. Logged in as National, then repeat key steps as State and LGA.",
        "features": [
            ("Members list with search and filters", "/admin/members", "All admins (scoped)"),
            ("Promote a member to State/Zonal/LGA/Cluster admin or Agent", "/admin/members/{type}/{id}/promote", "All admins (below own level)"),
            ("Bulk-promote up to 100 members to Agent (auto passwords)", "/admin/members/bulk-promote-agents", "All admins (scoped)"),
        ],
        "cases": [
            ("Open Members.", "Registrations and chapter members are combined and sorted by name, with a “Promoted as ...” badge where applicable.", "H"),
            ("With more than 50 members in view, page through the Members list.", "50 per page, with pagination links. Names stay in A–Z order across pages, with nobody missing or repeated. Search and filters stay applied when changing page. [Fixed in PR #1]", "H"),
            ("Search by part of a name and by part of an email. Filter by State, LGA and Ward.", "Results narrow correctly. Filters combine.", "H"),
            ("As a State admin, open Members.", "Only members in their state.", "H"),
            ("Promote form: check the Role list as National, State, Zonal, LGA and Cluster.", "Only roles BELOW your own, plus Agent. Cluster sees Agent only.", "H"),
            ("Promote to State admin: choose a state, enter email and password (≥8 characters). Save.", "Success message. A new admin appears in Admins. They can log in and are forced to change their password.", "H"),
            ("Promote to Zonal without a zone, or to LGA without an LGA.", "Error “Select a state and zone” / “Select a state and LGA”.", "H"),
            ("As a State admin (Kano), try to promote someone to an LGA admin in another state (DevTools).", "“That scope is outside your own jurisdiction.”", "H"),
            ("Promote to Cluster: search ward units and tick 3 polling units.", "Cluster admin is created with exactly those units.", "H"),
            ("Promote to Cluster/Agent with no units ticked.", "“Select at least one polling unit.”", "H"),
            ("Promote to Agent with units outside your jurisdiction (DevTools).", "“One or more selected polling units are outside your jurisdiction.”", "H"),
            ("Promote using an email already used by an admin, or by an agent.", "“An admin/agent with this email already exists.”", "H"),
            ("Try to promote the same member a second time.", "“This member has already been promoted.”", "H"),
            ("Promoted agent logs in at /agent/login with the password you set.", "Forced to change the password, then sees their assigned units.", "H"),
            ("Bulk: tick 3 members (one already promoted, one with an unmatched polling unit, one valid). Click bulk promote.", "Result page: valid = success with email + GENERATED PASSWORD + unit, already promoted = skipped, unmatched = error. Copy the password now, because it is shown only once.", "H"),
            ("Bulk-promote more than 100 members at once.", "Validation error (max 100).", "M"),
            ("Log in as a bulk-created agent using the generated password.", "Works and forces a password change.", "H"),
            ("Activity log after each promotion.", "member.promoted entries with role, scope and unit count.", "M"),
        ],
    },
    {
        "code": "AM",
        "title": "Admin – Admins Management (hierarchy)",
        "pre": "Admins exist at every level in 2 states.",
        "features": [
            ("Admins list (downline only), edit scope/active, assign units to Cluster, remove", "/admin/admins", "National, State, Zonal, LGA"),
        ],
        "cases": [
            ("National opens Admins.", "Sees all other admins (not themselves).", "H"),
            ("State admin opens Admins.", "Sees only Zonal/LGA/Cluster admins in their own state.", "H"),
            ("Zonal opens Admins. Then LGA opens Admins.", "Zonal sees LGA and Cluster in their zone. LGA sees Cluster in their LGA only.", "H"),
            ("Cluster opens Admins.", "Empty list (no downline).", "M"),
            ("State admin opens the edit URL of an admin in another state, or of a National admin.", "403.", "H"),
            ("Edit an LGA admin: change the LGA within your scope.", "Saved. The zone is derived automatically.", "M"),
            ("Edit scope to an area outside your jurisdiction (DevTools).", "“That scope is outside your own jurisdiction.”", "H"),
            ("Deactivate an admin.", "Saved. That admin is logged out on their next click (see AL).", "H"),
            ("Try to deactivate or remove the LAST active National admin.", "Blocked: “Can't deactivate/remove the last active National administrator.”", "H"),
            ("Try to remove your own account.", "403 “You can't remove your own account.”", "H"),
            ("Cluster admin: assign a polling unit, then unassign it.", "“Polling unit assigned/unassigned.” The cluster’s visible data changes accordingly.", "H"),
            ("Assign a unit outside your jurisdiction (DevTools).", "403.", "H"),
            ("Remove an admin.", "“Admin removed.” They can't log in. Listed in Trash.", "H"),
        ],
    },
    {
        "code": "AG",
        "title": "Admin – Polling Agents",
        "pre": "Agents exist, some covering units in more than one LGA.",
        "features": [
            ("Agents list, edit (name/email/phone/password/active), assign/unassign units, remove", "/admin/polling-agents", "All admins (scoped)"),
        ],
        "cases": [
            ("Open Polling Agents as National, then as State and Cluster.", "Each sees only agents in their jurisdiction, with a unit count.", "H"),
            ("Edit an agent: change name, phone and email.", "“Agent updated.” Log records before/after.", "H"),
            ("Change email to one already used by another agent.", "Validation error (unique).", "H"),
            ("Set a new password for the agent.", "Agent must change it at next login. The log shows password_changed = true and never the password itself.", "H"),
            ("Untick Active.", "Agent is blocked on their next request (403 deactivated) and can't log in.", "H"),
            ("Assign a unit by searching state → LGA → ward.", "Only units in your jurisdiction are listed. Unit added.", "H"),
            ("Unassign a unit.", "Unit removed. The agent can no longer open or report it (403).", "H"),
            ("Agent covers units in LGA-A and LGA-B. LGA-A admin tries to edit, deactivate or delete the agent.", "403. Account-level control needs authority over ALL of the agent's units.", "H"),
            ("Remove an agent.", "Soft-deleted to Trash. They can't log in.", "H"),
        ],
    },
    # ------------------------------------------------------------------- AGENT
    {
        "code": "AP",
        "title": "Agent Portal – Login, Password & Dashboard",
        "pre": "Agent accounts: active with 2+ units; new (must change password); deactivated.",
        "features": [
            ("Agent login/logout, forced password change, dashboard of assigned units", "/agent/login, /agent", "Agent"),
        ],
        "cases": [
            ("Open /agent while logged out.", "Redirects to /agent/login.", "H"),
            ("Valid login.", "Dashboard lists ONLY the agent’s assigned units (state/LGA/ward/unit) with the report status for each active election.", "H"),
            ("Wrong password, then 5 wrong attempts.", "Generic error, then “Too many login attempts...” lockout.", "H"),
            ("Deactivated agent logs in.", "“This agent account has been deactivated.” No access.", "H"),
            ("First login of a new agent.", "Forced to the change-password page until changed.", "H"),
            ("Change password: wrong current password, fewer than 8 characters, mismatch, then valid.", "Matching errors, then “Password changed.”", "H"),
            ("Admin credentials on /agent/login.", "Rejected.", "H"),
            ("Logged-in agent opens /admin.", "Redirected to the admin login. No admin access.", "H"),
            ("Logout, then Back button.", "Session ended.", "M"),
            ("Use the portal on a low-end Android phone over 3G.", "Pages load in a usable time. Buttons are big enough to tap.", "H"),
        ],
    },
    {
        "code": "RS",
        "title": "Agent – Result Submission & Resubmission",
        "pre": "Election(s) active with active candidates for the agent’s unit scope. Scoresheet photo (JPG) and PDF under 10 MB.",
        "features": [
            ("Multi-election report form: voters, votes per party/candidate, scoresheet upload, draft autosave", "/agent/units/{unit}/report", "Agent"),
            ("Agent views own scoresheet", "/agent/results/{id}/scoresheet", "Agent"),
        ],
        "cases": [
            ("Open Report for an assigned unit.", "One section per ACTIVE election that has active candidates for this unit’s state/zone/constituency. Only those parties are listed.", "H"),
            ("Open the report URL of a unit NOT assigned to you.", "403.", "H"),
            ("Fill all numbers correctly (party votes add up to valid votes) and attach a scoresheet in every section. Click “Submit All Reports”.", "“Results submitted for review.” The dashboard shows status Pending.", "H"),
            ("Party votes that do NOT add up to valid votes.", "Error “Party votes must add up to valid votes.” Nothing saved for ANY election (all-or-nothing).", "H"),
            ("Leave out the scoresheet in one section.", "Error on that section. Nothing saved. Uploaded files from other sections are discarded.", "H"),
            ("Scoresheet types: JPG, PNG, PDF (pass). GIF, DOCX, and a file over 10 MB (fail).", "Allowed types accepted. Others rejected with a clear message.", "H"),
            ("Negative numbers, decimals, letters, and 4294967296 (above the maximum).", "Rejected. Only whole numbers from 0 to 4,294,967,295.", "H"),
            ("Accredited > registered, or valid + rejected > accredited.", "Submission ALLOWED but flagged as an anomaly for admin review. The on-form sanity check warns the agent.", "H"),
            ("Accredited < votes cast is fine (fewer votes than accredited).", "Accepted with no anomaly.", "M"),
            ("Draft autosave: type some numbers, close the tab, reopen the form.", "“Restore draft” banner appears and restores the numbers. Scoresheet must be re-attached. The draft is cleared after a successful submit.", "M"),
            ("Resubmit the same unit with corrected figures.", "Accepted. The version number goes up and status resets to Pending. The previous version and scoresheet are kept in history.", "H"),
            ("Stale form: open the form in 2 tabs, submit in tab 1, then submit in tab 2.", "Tab 2 gets HTTP 409 “This result has changed. Reload the page...”. No overwrite.", "H"),
            ("Admin deactivates the election while the agent has the form open. Agent submits.", "Section is skipped or rejected: “None of the submitted elections are currently open” or a skipped notice.", "M"),
            ("Admin changes the candidate list while the agent has the form open. Agent submits.", "Error “Enter votes for every candidate on this ballot... Reload the form”.", "M"),
            ("Agent deactivated mid-session, then submits.", "403. Nothing saved.", "H"),
            ("Open your own scoresheet link. Then change the id to another agent’s result.", "Own file opens. Another agent’s file gives 403.", "H"),
            ("Submit from a phone using the camera to capture the scoresheet.", "Camera capture works. The upload completes on a mobile network.", "H"),
        ],
    },
    # --------------------------------------------------------------- RESULTS
    {
        "code": "RV",
        "title": "Admin – Result Review (verify / flag / history)",
        "pre": "Pending results exist: one clean, one with an anomaly, one resubmitted twice.",
        "features": [
            ("Results queue by election and status (pending/verified/flagged/all)", "/admin/polling-results", "All admins (scoped)"),
            ("Review & history: figures, scoresheet per version, audit log, verify/flag", "/admin/polling-results/{id}", "All admins (scoped)"),
        ],
        "cases": [
            ("Open Result Review. Switch the election tabs and the status tabs.", "Lists filter correctly, newest submitted first, only units in your jurisdiction.", "H"),
            ("Click the scoresheet link in the list.", "Opens the current scoresheet in a new tab (image or PDF).", "H"),
            ("Open “Review & history” for a clean result.", "Shows the counts, party votes, current version scoresheet, earlier submissions and audit log.", "H"),
            ("Verify a clean result.", "“Review recorded.” Status becomes Verified, with verifier and time recorded. It now counts in the situation room.", "H"),
            ("Verify an ANOMALY result with no reason, or a reason under 10 characters.", "Error: must explain why (at least 10 characters).", "H"),
            ("Verify the anomaly result with a 10+ character reason.", "Verified. The note is saved and visible in the log.", "H"),
            ("Flag a result (with or without a reason).", "Status becomes Flagged. It is excluded from the totals.", "H"),
            ("Open the same result in 2 tabs and verify in both.", "The second gets 409 “This result has changed...”.", "H"),
            ("Agent resubmits after verification.", "Status goes back to Pending. The old verified figures stop counting. A new version appears in history.", "H"),
            ("Open each older version’s scoresheet from history.", "The correct historical file opens for each version.", "M"),
            ("State admin opens a result from another state by URL, including its scoresheet URL.", "403.", "H"),
            ("Change the submission id in the scoresheet URL to one from another result.", "404.", "M"),
        ],
    },
    {
        "code": "SR",
        "title": "Situation Room (live dashboard)",
        "pre": "Verified, pending and flagged results in at least 2 states and 2 elections.",
        "features": [
            ("Live situation room: progress, party totals, scoreboard, state breakdown, anomalies, recent activity. Auto-refresh every 20 s", "/admin/situation-room (+ /summary JSON)", "All admins (scoped)"),
        ],
        "cases": [
            ("Open the Situation Room. Use the election switcher.", "The page reloads for the chosen election. It defaults to the first ACTIVE election.", "H"),
            ("Progress: compare with the Result Review counts.", "Assigned units, reported, verified, flagged and pending all match.", "H"),
            ("Party totals: add up the verified results by hand for 3–5 units.", "Totals match exactly. Pending and flagged results are NOT counted.", "H"),
            ("Presidential: candidate name and photo shown per party.", "Correct candidate for each party.", "M"),
            ("Governorship/Senatorial scoreboard.", "Each state/zone shows the leader, or Tied / No votes correctly. The “leading in N” counts are right.", "H"),
            ("Presidential state breakdown.", "Units verified and valid votes per state are correct.", "M"),
            ("Anomalies panel.", "Lists unverified results with inconsistent figures. The links open the result.", "H"),
            ("Recent activity.", "Latest 15 submit/resubmit/verify/flag actions with actor and time.", "M"),
            ("Leave the page open, verify a result in another tab, wait 20 s.", "Figures update automatically without a manual reload.", "H"),
            ("State and Cluster admins open the Situation Room.", "Figures cover ONLY their jurisdiction.", "H"),
            ("Situation room on a projector/TV (1920 px) and on a phone.", "Readable. Charts and tables don't overflow.", "M"),
            ("Leave it running for 30 minutes.", "No memory growth or freezing. Session expiry is handled (does not silently show stale data).", "M"),
        ],
    },
    {
        "code": "TR",
        "title": "Trash (restore / permanent delete)",
        "pre": "One deleted item of each type: admin, agent, party, candidate, news, team.",
        "features": [
            ("Trash: restore or permanently delete removed records", "/admin/trash", "All admins (scoped; content types National only)"),
        ],
        "cases": [
            ("National opens Trash.", "All 6 types are listed with their deleted dates.", "H"),
            ("State admin opens Trash.", "Only admins and agents in their jurisdiction. No party/candidate/news/team sections.", "H"),
            ("Restore each type.", "“... restored.” The item reappears in its list and on the public site where relevant.", "H"),
            ("Restore an agent whose email has since been reused by a new agent.", "Clear conflict message: “Something else already uses the same email...”", "M"),
            ("Permanently delete a news item and a team member with images.", "Gone for good. The image URL now gives 404.", "H"),
            ("State admin tries to restore or delete a news item by URL/DevTools.", "403.", "H"),
            ("Restore one item and permanently delete another, then open the Activity Log.", "Entries such as news.restored and news.force_deleted appear, with the admin’s name and the item’s title. [Fixed in PR #1]", "M"),
        ],
    },
    {
        "code": "LG",
        "title": "Activity Log (National only)",
        "pre": "Some actions performed by different admins.",
        "features": [
            ("Admin activity log with actor / action / date filters", "/admin/activity-log", "National"),
        ],
        "cases": [
            ("Open the Activity Log.", "Newest first, 20 per page, showing actor, action, subject and time.", "H"),
            ("Filter by actor name (partial), by action, and by date range.", "Results filter correctly. Filters stay applied across pages.", "M"),
            ("Check which actions are logged: party, candidate, election, admin, agent, member promotion, news, team and trash restore/permanent delete.", "Each shows the correct actor and before/after details. Passwords are never shown.", "H"),
            ("Try to edit or delete a log entry (there should be no UI or route for it).", "Not possible. The log is append-only.", "M"),
            ("Non-National admin opens /admin/activity-log.", "403. Link not shown in the sidebar.", "H"),
            ("Create, edit and delete a News item and a Team member, then check the log.", "news.created/updated/removed and team.created/updated/removed entries appear. Updates show before/after values (e.g. Active on to off). [Fixed in PR #1]", "M"),
        ],
    },
    # ------------------------------------------------------------- CROSS-CUTTING
    {
        "code": "RB",
        "title": "Role & Jurisdiction Access (also fill in the Section 6 matrix)",
        "pre": "One account per role: National; State (Kano); Zonal (a Kano zone); LGA (a Kano LGA); Cluster (3 Kano units); Agent (1 unit); and a second State (Lagos) for cross-checks.",
        "features": [],
        "cases": [
            ("For every role, try each admin URL from the Section 6 matrix directly in the address bar.", "Every cell matches the expected Allow/403/Login result.", "H"),
            ("Kano State admin: Members, Signups, Agents, Results, Situation Room.", "Kano data only. Nothing from Lagos anywhere.", "H"),
            ("Kano State admin: open a Lagos member’s promote URL, a Lagos agent’s edit URL and a Lagos result URL.", "403 on each.", "H"),
            ("Cluster admin: only their 3 assigned units’ members, agents and results.", "Nothing from other units in the same LGA.", "H"),
            ("Agent: guess another unit’s report URL (/agent/units/{id}/report).", "403.", "H"),
            ("Deactivate a State admin who has a downline.", "Downline admins and agents are unaffected. The State admin is blocked.", "M"),
        ],
    },
    {
        "code": "SC",
        "title": "Security (manual checks)",
        "pre": "Use browser DevTools. Optional: securityheaders.com and SSL Labs.",
        "features": [],
        "cases": [
            ("Run https://sufisupporthub.com through securityheaders.com.", "Strict-Transport-Security, X-Frame-Options SAMEORIGIN, X-Content-Type-Options nosniff, Referrer-Policy, Permissions-Policy and Content-Security-Policy are all present.", "H"),
            ("Run the domain through SSL Labs.", "Grade A or better. TLS 1.2+ only.", "M"),
            ("Try to load the site inside an <iframe> on another domain (e.g. a codepen).", "Blocked (frame-ancestors 'self').", "M"),
            ("Submit any admin form after deleting the _token hidden field (DevTools).", "419 Page Expired. The action is not performed.", "H"),
            ("Inspect the cookies after login.", "The session cookie is HttpOnly and Secure (HTTPS). No password or PII is in the cookies or localStorage (the agent draft holds numbers only).", "H"),
            ("Enter XSS payloads in every text field (signup name, news title/body, team bio, party name, candidate name, verification reason, activity filters).", "Always displayed as text, never executed, in both admin and public pages.", "H"),
            ("SQL-style input in search/filters, e.g. ' OR 1=1 --.", "Treated as plain text. No error and no extra data.", "H"),
            ("Change ids in admin/agent URLs to records you shouldn’t see (IDOR).", "403 or 404 every time.", "H"),
            ("Upload a PHP file renamed to .jpg as a team photo or scoresheet.", "Rejected, or stored safely as an image and never executed.", "H"),
            ("Confirm that scoresheets are private: copy a scoresheet link, log out, open it.", "Redirected to login. Not accessible.", "H"),
            ("Check that error pages and page source have no secrets (APP_KEY, DB password, file paths).", "None visible.", "H"),
            ("Password policy: try an 8-character common password such as “password”.", "Accepted by the current rules (min 8). Record it for a policy decision.", "L"),
        ],
    },
    {
        "code": "PF",
        "title": "Performance",
        "pre": "Use Chrome DevTools Lighthouse (mobile) and PageSpeed Insights.",
        "features": [],
        "cases": [
            ("Lighthouse mobile on /, /news, /join-chapter and /poster.", "Performance ≥ 70, LCP < 2.5 s, CLS < 0.1. Record the scores each release.", "M"),
            ("Homepage hero and news images.", "Images are compressed and sized sensibly (the hero PNG should not be several MB).", "M"),
            ("Location dropdowns for a large state (e.g. Kano, Lagos).", "Unit list loads in under 2 s.", "M"),
            ("Situation room with realistic data (e.g. 5,000+ verified results).", "Page and /summary respond in under 3 s. The 20 s refresh does not overload the server.", "H"),
            ("Members page as National with a large number of registrations.", "Page 1 loads quickly even with thousands of signups, because only 50 rows are loaded per page. Check this on the live MySQL database.", "H"),
            ("Election-day simulation: 10–20 testers submit results at the same time.", "All submissions succeed or get clear errors. No timeouts or lost scoresheets.", "H"),
        ],
    },
    {
        "code": "CB",
        "title": "Browsers, Devices & Responsive Layout",
        "pre": "See the environment table in Section 2.3.",
        "features": [],
        "cases": [
            ("Run the smoke checklist (Section 7) in Chrome, Edge, Firefox and Safari on desktop.", "Same behaviour and layout in all four.", "H"),
            ("Public pages at 320, 375, 414, 768, 1024, 1366 and 1920 px widths.", "No horizontal scrolling, overlapping text or cut-off buttons.", "H"),
            ("Agent portal and result form on Android Chrome and iPhone Safari.", "Fully usable with a numeric keypad for number fields.", "H"),
            ("Admin panel on a tablet.", "Usable. Tables scroll.", "M"),
            ("Rotate the phone between portrait and landscape on the modal, poster and agent form.", "Layout adapts. No data lost.", "M"),
        ],
    },
    {
        "code": "AX",
        "title": "Accessibility",
        "pre": "Use Lighthouse Accessibility and keyboard-only navigation.",
        "features": [],
        "cases": [
            ("Lighthouse Accessibility on the public pages.", "Score ≥ 85. Record the issues.", "M"),
            ("Keyboard only: Tab through the homepage, open the modal, fill it and submit.", "Focus is visible and in a logical order. The modal can be closed with Esc or X by keyboard.", "M"),
            ("All images have meaningful alt text (hero, team photos, news images).", "Alt text present.", "L"),
            ("Form fields have labels. Errors are announced or visible next to the field.", "Labels present. Errors are clear.", "M"),
            ("Colour contrast of green text and buttons.", "Meets WCAG AA (4.5:1 for normal text).", "L"),
        ],
    },
    {
        "code": "OP",
        "title": "Deployment, Data & Operations",
        "pre": "Coordinate with whoever manages the cPanel hosting and the GitHub repository.",
        "features": [
            ("Auto-deploy on push to the production branch (GitHub Actions → FTP → deploy hook)", "GitHub Actions", "Developer"),
        ],
        "cases": [
            ("Push a harmless change to the production branch.", "GitHub Actions run passes: tests → build → FTP upload → deploy hook HTTP 200. The change is live.", "H"),
            ("After deploy, check that storage/app/private scoresheets, uploads (news/team/party/candidate images) and sessions survived.", "Nothing is lost or overwritten by the deploy.", "H"),
            ("Pending migrations after deploy.", "They ran automatically. No 500 errors on pages that use new columns.", "H"),
            ("Polling-unit data: count the states, LGAs and units in the database vs the CSV.", "Counts match (176k+ units). No duplicates after re-running the seeder.", "M"),
            ("Backups: confirm that database AND storage/app/private backups exist and a restore has been tried.", "Backup is recent, and a restore on staging works.", "H"),
            ("Admin seed: check that ADMIN_EMAIL/ADMIN_PASSWORD exist and the default admin password has been changed.", "No default or weak credentials in production.", "H"),
            ("Mail configuration.", "MAIL_MAILER is not “log” in production, if any feature sends email in future.", "L"),
            ("Clean-up after testing: remove test registrations, agents, results and news.", "Production data contains no test records (or they are clearly labelled and excluded from totals).", "H"),
        ],
    },
]


# Section 6: expected access per role. A = allowed; 403 = forbidden;
# L = redirected to the relevant login page; "own" = only own jurisdiction/units.
ACCESS_ROLES = ["Visitor", "Agent", "Cluster", "LGA", "Zonal", "State", "National"]
ACCESS_MATRIX = [
    ("/ , /news, /team, /join-chapter, /poster", ["A", "A", "A", "A", "A", "A", "A"]),
    ("/admin (dashboard)", ["L", "L", "A", "A", "A", "A", "A"]),
    ("/admin/signups, /admin/members", ["L", "L", "own", "own", "own", "own", "A"]),
    ("/admin/team, /news, /parties, /elections", ["L", "L", "403", "403", "403", "403", "A"]),
    ("/admin/activity-log", ["L", "L", "403", "403", "403", "403", "A"]),
    ("/admin/admins", ["L", "L", "empty", "own", "own", "own", "A"]),
    ("/admin/polling-agents", ["L", "L", "own", "own", "own", "own", "A"]),
    ("/admin/polling-results, /situation-room", ["L", "L", "own", "own", "own", "own", "A"]),
    ("/admin/trash", ["L", "L", "own*", "own*", "own*", "own*", "A"]),
    ("/agent (dashboard, own units)", ["L", "A", "L", "L", "L", "L", "L"]),
    ("/agent/units/{other unit}/report", ["L", "403", "L", "L", "L", "L", "L"]),
]

# Issues spotted while reading the source, with their current status.
# (module, finding, status, how to retest / decision needed)
FIXED = "Fixed in PR #1"
OPEN = "Open (owner decision)"
CODE_REVIEW_FINDINGS = [
    ("HP", "Nav and footer links pointed to sections that don’t exist (#about, #events, #volunteer, #donate), and Contact had no target.", FIXED, "HP-03, HP-14"),
    ("HP", "Footer social icons all pointed to “#”.", FIXED, "HP-15, HP-16 (icons hidden until SOCIAL_*_URL is set)"),
    ("HP", "“Across Nigeria” cards showed made-up chapter counts and only popped up an alert.", FIXED, "HP-13"),
    ("CH", "/join-chapter didn’t show validation errors, so a rejected form reloaded silently.", FIXED, "CH-06, CH-07"),
    ("CH", "The success message promised contact “via email”, but no email is sent.", FIXED, "CH-02, CH-04"),
    ("RG/CH", "README said a repeat sign-up updates the details. The code (deliberately) keeps the original.", FIXED, "README corrected; RG-07, CH-05 unchanged"),
    ("AD", "Dashboard showed national totals to every admin role.", FIXED, "AD-01, AD-02"),
    ("AD", "Team, News, Parties and Elections sidebar links were shown to all roles, but gave 403 below National.", FIXED, "AD-04"),
    ("ME/PF", "Members page loaded every member at once (no pagination).", FIXED, "ME-02, PF-05"),
    ("TR/LG", "Trash restore/permanent delete and News/Team changes were not in the Activity Log.", FIXED, "TR-07, LG-03, LG-06"),
    ("HO", "robots.txt didn’t reference /sitemap.xml.", FIXED, "HO-12"),
    ("HP", "Footer “Privacy Policy | Terms of Service” are plain text with no pages, although personal data is collected.", OPEN, "Owner to supply policy text (NDPR)"),
    ("HP", "Footer contact is support@innofiniti.ng / +234 706 779 7009.", OPEN, "Owner to confirm the right SSH contacts"),
    ("HO", "logo.png is marked in the README as a placeholder.", OPEN, "Owner to supply final logo files"),
]
